### ISSUE TITLE
Extremely low coverage for a few languages

### ISSUE THREAD

**Issue by LinguList** [lexibank/chacolanguages#6]
I should've run this earlier, but now I did it and we need to revise our account on the data:

The last line in the following table is the proportion of concepts attested from teh overall number of 324 concepts:

```-------------------  ---  ---  ----
Abipón               215  154  0.48
Ava Guaraní          262  214  0.66
Ayoreo               375  227  0.70
Chamacoco            250  162  0.50
Enlhet               437  251  0.77
Enxet Sur            333  208  0.64
Guaraní Izoceño       24   24  0.07
Guaraní Paraguayo    323  237  0.73
Iyojwa'ja Chorote    358  272  0.84
Iyoʼwujwa Chorote    254  190  0.59
Iyówuj'wa             45   37  0.11
Kadiweo              224  157  0.48
Lule                 294  173  0.53
Maká                 281  242  0.75
Mapudungun           254  206  0.64
Mbya                 222  167  0.52
Mocoví               297  215  0.66
Nivaclé              373  248  0.77
Pilagá               286  248  0.77
Quichua Santiagueño  235  176  0.54
Tapiete              271  202  0.62
Toba                 470  273  0.84
Toba de Cerrito      179  153  0.47
Toba-pilagá          367  254  0.78
Vilela                73   60  0.19
Wichí                387  241  0.74
-------------------  ---  ---  ----
```

**Comment by Bridnicolas** [comment]
That's great.

**Comment by Bridnicolas** [comment]
No, wait wait. What is "iyówuj'wa". On the list. It's repeated. Chorote Iyowujwa.

**Comment by LinguList** [comment]
Oh dear, so can you please check the file `etc/languages.tsv`, what is happening there? We must have two entries then!

**Comment by LinguList** [comment]
Ah, yes, check that list: the ID says "Manjuy", so the name is probably different, right? Can you fix that? Then I re-run, correcting is no problem, we make a release version 0.2 then!

**Comment by Bridnicolas** [comment]
Yes. Done. It's correct now.

**Comment by LinguList** [comment]
Oh. You modifed the ID as well, but the ID should not be touched!

**Comment by Bridnicolas** [comment]
Are you sure? Not right now. I only changed Manjui, and Iyówuj'wa for Iyo'wujwa' Chorote, both under the Name column.

**Comment by LinguList** [comment]
Okay, I'll check again.

**Comment by LinguList** [comment]
You modified the geo-coordinates. They are wrong for Cerriteno and TobaPilaga now, for this reason, compilation fails. Can you check please?

**Comment by Bridnicolas** [comment]
Yes, now I see. Can't imagine how that happened. I'll fix it now

**Comment by Bridnicolas** [comment]
Done

**Comment by LinguList** [comment]
Works now
